import "./globals.css";
import Navbar from "../components/navbar/Navbar";
import Sidebar from "@/components/sidebar/Sidebar";
import Footer from "@/components/footer/Footer";

export const metadata = {
  title: "Portafolio JuniorSolis",
  description: "Generated by JuniorSolis Developer Web",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body
        className="flex flex-col min-h-screen bg-background text-foreground"
      >
        <div className="flex flex-1">
          <Sidebar />
          <div className="flex flex-col w-full">
            <Navbar />
            

            <main className="flex-1 p-4">{children}</main>
            <Footer />
          </div>
        </div>
      </body>
    </html>
  );
}
