import "./globals.css";
import Navbar from "../components/navbar/Navbar";

export const metadata = {
  title: "Portafolio JuniorSolis",
  description: "Generated by JuniorSolis Developer Web",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body
        className="flex flex-col min-h-screen bg-background text-foreground"
      >
        <div className="flex flex-col w-full">
          <Navbar />

        </div>
        <main className="flex-1 p-4">{children}</main>
      </body>
    </html>
  );
}
